namespace ManajemenLaundrySepatu
{
    partial class FormBAK
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle7 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle8 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle9 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle10 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle11 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle12 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle13 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle14 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle15 = new System.Windows.Forms.DataGridViewCellStyle();
            this.sfdBackup = new System.Windows.Forms.SaveFileDialog();
            this.ofdRestore = new System.Windows.Forms.OpenFileDialog();
            this.btnShowCachePelanggan = new ManajemenLaundrySepatu.WinForms.Helpers.MyMaterialButton();
            this.btnRefreshDataPelanggan = new ManajemenLaundrySepatu.WinForms.Helpers.MyMaterialButton();
            this.btnBackup = new ManajemenLaundrySepatu.WinForms.Helpers.MyMaterialButton();
            this.btnRestore = new ManajemenLaundrySepatu.WinForms.Helpers.MyMaterialButton();
            this.btnKembali = new ManajemenLaundrySepatu.WinForms.Helpers.MyMaterialButton();
            this.pbBR = new System.Windows.Forms.ProgressBar();
            this.lblLastBackup = new MaterialSkin.Controls.MaterialLabel();
            this.tabPreview = new System.Windows.Forms.TabControl();
            this.tabPelanggan = new System.Windows.Forms.TabPage();
            this.dgvPelanggan = new System.Windows.Forms.DataGridView();
            this.tabSepatu = new System.Windows.Forms.TabPage();
            this.dgvSepatu = new System.Windows.Forms.DataGridView();
            this.tabBarangKonsumsi = new System.Windows.Forms.TabPage();
            this.dgvBarangKonsumsi = new System.Windows.Forms.DataGridView();
            this.tabMaintenanceAlatLaundry = new System.Windows.Forms.TabPage();
            this.dgvMaintenanceAlatLaundry = new System.Windows.Forms.DataGridView();
            this.tabTransaksi = new System.Windows.Forms.TabPage();
            this.dgvTransaksi = new System.Windows.Forms.DataGridView();
            this.tabPreview.SuspendLayout();
            this.tabPelanggan.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPelanggan)).BeginInit();
            this.tabSepatu.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvSepatu)).BeginInit();
            this.tabBarangKonsumsi.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvBarangKonsumsi)).BeginInit();
            this.tabMaintenanceAlatLaundry.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvMaintenanceAlatLaundry)).BeginInit();
            this.tabTransaksi.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvTransaksi)).BeginInit();
            this.SuspendLayout();
            this.themeSwitch.Location = new System.Drawing.Point(629, 24);
            this.themeSwitch.Size = new System.Drawing.Size(170, 39);
            this.ofdRestore.FileName = "Restore";
            this.btnShowCachePelanggan.AutoSize = false;
            this.btnShowCachePelanggan.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.btnShowCachePelanggan.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.btnShowCachePelanggan.Density = ManajemenLaundrySepatu.WinForms.Helpers.MyMaterialButton.MaterialButtonDensity.Default;
            this.btnShowCachePelanggan.Depth = 0;
            this.btnShowCachePelanggan.FlatAppearance.BorderColor = System.Drawing.SystemColors.ButtonFace;
            this.btnShowCachePelanggan.FlatAppearance.CheckedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(54)))), ((int)(((byte)(82)))), ((int)(((byte)(104)))));
            this.btnShowCachePelanggan.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.btnShowCachePelanggan.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnShowCachePelanggan.HighEmphasis = true;
            this.btnShowCachePelanggan.Icon = null;
            this.btnShowCachePelanggan.Location = new System.Drawing.Point(126, 405);
            this.btnShowCachePelanggan.Margin = new System.Windows.Forms.Padding(4, 6, 4, 6);
            this.btnShowCachePelanggan.MouseState = MaterialSkin.MouseState.HOVER;
            this.btnShowCachePelanggan.Name = "btnShowCachePelanggan";
            this.btnShowCachePelanggan.NoAccentTextColor = System.Drawing.Color.Empty;
            this.btnShowCachePelanggan.Size = new System.Drawing.Size(69, 36);
            this.btnShowCachePelanggan.TabIndex = 5;
            this.btnShowCachePelanggan.Text = "Cache";
            this.btnShowCachePelanggan.Type = ManajemenLaundrySepatu.WinForms.Helpers.MyMaterialButton.MaterialButtonType.Contained;
            this.btnShowCachePelanggan.UseAccentColor = false;
            this.btnShowCachePelanggan.UseVisualStyleBackColor = false;
            this.btnShowCachePelanggan.Click += new System.EventHandler(this.btnShowCacheTransaksi_Click);
            this.btnRefreshDataPelanggan.AutoSize = false;
            this.btnRefreshDataPelanggan.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.btnRefreshDataPelanggan.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.btnRefreshDataPelanggan.Density = ManajemenLaundrySepatu.WinForms.Helpers.MyMaterialButton.MaterialButtonDensity.Default;
            this.btnRefreshDataPelanggan.Depth = 0;
            this.btnRefreshDataPelanggan.FlatAppearance.BorderColor = System.Drawing.SystemColors.ButtonFace;
            this.btnRefreshDataPelanggan.FlatAppearance.CheckedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(54)))), ((int)(((byte)(82)))), ((int)(((byte)(104)))));
            this.btnRefreshDataPelanggan.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.btnRefreshDataPelanggan.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnRefreshDataPelanggan.HighEmphasis = true;
            this.btnRefreshDataPelanggan.Icon = null;
            this.btnRefreshDataPelanggan.Location = new System.Drawing.Point(235, 405);
            this.btnRefreshDataPelanggan.Margin = new System.Windows.Forms.Padding(4, 6, 4, 6);
            this.btnRefreshDataPelanggan.MouseState = MaterialSkin.MouseState.HOVER;
            this.btnRefreshDataPelanggan.Name = "btnRefreshDataPelanggan";
            this.btnRefreshDataPelanggan.NoAccentTextColor = System.Drawing.Color.Empty;
            this.btnRefreshDataPelanggan.Size = new System.Drawing.Size(84, 36);
            this.btnRefreshDataPelanggan.TabIndex = 4;
            this.btnRefreshDataPelanggan.Text = "Refresh";
            this.btnRefreshDataPelanggan.Type = ManajemenLaundrySepatu.WinForms.Helpers.MyMaterialButton.MaterialButtonType.Contained;
            this.btnRefreshDataPelanggan.UseAccentColor = false;
            this.btnRefreshDataPelanggan.UseVisualStyleBackColor = false;
            this.btnRefreshDataPelanggan.Click += new System.EventHandler(this.btnRefreshDataTransaksi_Click);
            this.btnBackup.AutoSize = false;
            this.btnBackup.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.btnBackup.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.btnBackup.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnBackup.Density = ManajemenLaundrySepatu.WinForms.Helpers.MyMaterialButton.MaterialButtonDensity.Default;
            this.btnBackup.Depth = 0;
            this.btnBackup.FlatAppearance.BorderColor = System.Drawing.SystemColors.ButtonFace;
            this.btnBackup.FlatAppearance.CheckedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(54)))), ((int)(((byte)(82)))), ((int)(((byte)(104)))));
            this.btnBackup.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.btnBackup.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnBackup.HighEmphasis = true;
            this.btnBackup.Icon = null;
            this.btnBackup.Location = new System.Drawing.Point(369, 405);
            this.btnBackup.Margin = new System.Windows.Forms.Padding(4, 6, 4, 6);
            this.btnBackup.MouseState = MaterialSkin.MouseState.HOVER;
            this.btnBackup.Name = "btnBackup";
            this.btnBackup.NoAccentTextColor = System.Drawing.Color.Empty;
            this.btnBackup.Size = new System.Drawing.Size(78, 36);
            this.btnBackup.TabIndex = 3;
            this.btnBackup.Text = "Backup";
            this.btnBackup.Type = ManajemenLaundrySepatu.WinForms.Helpers.MyMaterialButton.MaterialButtonType.Contained;
            this.btnBackup.UseAccentColor = false;
            this.btnBackup.UseVisualStyleBackColor = false;
            this.btnBackup.Click += new System.EventHandler(this.btnBackup_Click);
            this.btnRestore.AutoSize = false;
            this.btnRestore.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.btnRestore.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.btnRestore.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnRestore.Density = ManajemenLaundrySepatu.WinForms.Helpers.MyMaterialButton.MaterialButtonDensity.Default;
            this.btnRestore.Depth = 0;
            this.btnRestore.FlatAppearance.BorderColor = System.Drawing.SystemColors.ButtonFace;
            this.btnRestore.FlatAppearance.CheckedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(54)))), ((int)(((byte)(82)))), ((int)(((byte)(104)))));
            this.btnRestore.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.btnRestore.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnRestore.HighEmphasis = true;
            this.btnRestore.Icon = null;
            this.btnRestore.Location = new System.Drawing.Point(505, 405);
            this.btnRestore.Margin = new System.Windows.Forms.Padding(4, 6, 4, 6);
            this.btnRestore.MouseState = MaterialSkin.MouseState.HOVER;
            this.btnRestore.Name = "btnRestore";
            this.btnRestore.NoAccentTextColor = System.Drawing.Color.Empty;
            this.btnRestore.Size = new System.Drawing.Size(84, 36);
            this.btnRestore.TabIndex = 2;
            this.btnRestore.Text = "Restore";
            this.btnRestore.Type = ManajemenLaundrySepatu.WinForms.Helpers.MyMaterialButton.MaterialButtonType.Contained;
            this.btnRestore.UseAccentColor = false;
            this.btnRestore.UseVisualStyleBackColor = false;
            this.btnRestore.Click += new System.EventHandler(this.btnRestore_Click);
            this.btnKembali.AutoSize = false;
            this.btnKembali.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.btnKembali.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.btnKembali.Cursor = System.Windows.Forms.Cursors.Hand;
            this.btnKembali.Density = ManajemenLaundrySepatu.WinForms.Helpers.MyMaterialButton.MaterialButtonDensity.Default;
            this.btnKembali.Depth = 0;
            this.btnKembali.FlatAppearance.BorderColor = System.Drawing.SystemColors.ButtonFace;
            this.btnKembali.FlatAppearance.CheckedBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(136)))), ((int)(((byte)(54)))), ((int)(((byte)(82)))), ((int)(((byte)(104)))));
            this.btnKembali.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.btnKembali.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.btnKembali.HighEmphasis = true;
            this.btnKembali.Icon = null;
            this.btnKembali.Location = new System.Drawing.Point(7, 405);
            this.btnKembali.Margin = new System.Windows.Forms.Padding(4, 6, 4, 6);
            this.btnKembali.MouseState = MaterialSkin.MouseState.HOVER;
            this.btnKembali.Name = "btnKembali";
            this.btnKembali.NoAccentTextColor = System.Drawing.Color.Empty;
            this.btnKembali.Size = new System.Drawing.Size(83, 36);
            this.btnKembali.TabIndex = 6;
            this.btnKembali.Text = "Kembali";
            this.btnKembali.Type = ManajemenLaundrySepatu.WinForms.Helpers.MyMaterialButton.MaterialButtonType.Contained;
            this.btnKembali.UseAccentColor = false;
            this.btnKembali.UseVisualStyleBackColor = false;
            this.btnKembali.Click += new System.EventHandler(this.btnKembali_Click);
            this.pbBR.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.pbBR.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.pbBR.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.pbBR.Location = new System.Drawing.Point(435, 67);
            this.pbBR.Name = "pbBR";
            this.pbBR.Size = new System.Drawing.Size(359, 27);
            this.pbBR.TabIndex = 8;
            this.lblLastBackup.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.lblLastBackup.Depth = 0;
            this.lblLastBackup.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.lblLastBackup.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.lblLastBackup.Location = new System.Drawing.Point(11, 64);
            this.lblLastBackup.MouseState = MaterialSkin.MouseState.HOVER;
            this.lblLastBackup.Name = "lblLastBackup";
            this.lblLastBackup.Size = new System.Drawing.Size(352, 27);
            this.lblLastBackup.TabIndex = 7;
            this.lblLastBackup.Text = "Backup Terakhir";
            this.tabPreview.Controls.Add(this.tabPelanggan);
            this.tabPreview.Controls.Add(this.tabSepatu);
            this.tabPreview.Controls.Add(this.tabBarangKonsumsi);
            this.tabPreview.Controls.Add(this.tabMaintenanceAlatLaundry);
            this.tabPreview.Controls.Add(this.tabTransaksi);
            this.tabPreview.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.tabPreview.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            this.tabPreview.Location = new System.Drawing.Point(7, 100);
            this.tabPreview.Multiline = true;
            this.tabPreview.Name = "tabPreview";
            this.tabPreview.SelectedIndex = 4;
            this.tabPreview.Size = new System.Drawing.Size(787, 296);
            this.tabPreview.SizeMode = System.Windows.Forms.TabSizeMode.Fixed;
            this.tabPreview.TabIndex = 1;
            this.tabPelanggan.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.tabPelanggan.Controls.Add(this.dgvPelanggan);
            this.tabPelanggan.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tabPelanggan.Location = new System.Drawing.Point(4, 26);
            this.tabPelanggan.Name = "tabPelanggan";
            this.tabPelanggan.Padding = new System.Windows.Forms.Padding(3);
            this.tabPelanggan.Size = new System.Drawing.Size(779, 266);
            this.tabPelanggan.TabIndex = 0;
            this.tabPelanggan.Text = "Pelanggan";
            this.dgvPelanggan.BackgroundColor = System.Drawing.SystemColors.ButtonFace;
            this.dgvPelanggan.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle1.BackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle1.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            dataGridViewCellStyle1.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle1.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvPelanggan.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvPelanggan.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvPelanggan.DefaultCellStyle = dataGridViewCellStyle2;
            this.dgvPelanggan.EnableHeadersVisualStyles = false;
            this.dgvPelanggan.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.dgvPelanggan.GridColor = System.Drawing.SystemColors.ButtonFace;
            this.dgvPelanggan.Location = new System.Drawing.Point(3, 3);
            this.dgvPelanggan.Name = "dgvPelanggan";
            this.dgvPelanggan.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            dataGridViewCellStyle3.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvPelanggan.RowHeadersDefaultCellStyle = dataGridViewCellStyle3;
            this.dgvPelanggan.RowHeadersWidth = 62;
            this.dgvPelanggan.RowTemplate.Height = 28;
            this.dgvPelanggan.Size = new System.Drawing.Size(774, 260);
            this.dgvPelanggan.TabIndex = 21;
            this.tabSepatu.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.tabSepatu.Controls.Add(this.dgvSepatu);
            this.tabSepatu.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tabSepatu.Location = new System.Drawing.Point(4, 26);
            this.tabSepatu.Name = "tabSepatu";
            this.tabSepatu.Padding = new System.Windows.Forms.Padding(3);
            this.tabSepatu.Size = new System.Drawing.Size(779, 266);
            this.tabSepatu.TabIndex = 1;
            this.tabSepatu.Text = "Sepatu";
            this.dgvSepatu.BackgroundColor = System.Drawing.SystemColors.ButtonFace;
            this.dgvSepatu.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle4.BackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            dataGridViewCellStyle4.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvSepatu.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle4;
            this.dgvSepatu.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle5.BackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvSepatu.DefaultCellStyle = dataGridViewCellStyle5;
            this.dgvSepatu.EnableHeadersVisualStyles = false;
            this.dgvSepatu.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.dgvSepatu.GridColor = System.Drawing.SystemColors.ButtonFace;
            this.dgvSepatu.Location = new System.Drawing.Point(3, 3);
            this.dgvSepatu.Name = "dgvSepatu";
            this.dgvSepatu.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle6.BackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            dataGridViewCellStyle6.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvSepatu.RowHeadersDefaultCellStyle = dataGridViewCellStyle6;
            this.dgvSepatu.RowHeadersWidth = 62;
            this.dgvSepatu.RowTemplate.Height = 28;
            this.dgvSepatu.Size = new System.Drawing.Size(774, 260);
            this.dgvSepatu.TabIndex = 31;
            this.tabBarangKonsumsi.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.tabBarangKonsumsi.Controls.Add(this.dgvBarangKonsumsi);
            this.tabBarangKonsumsi.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tabBarangKonsumsi.Location = new System.Drawing.Point(4, 26);
            this.tabBarangKonsumsi.Name = "tabBarangKonsumsi";
            this.tabBarangKonsumsi.Size = new System.Drawing.Size(779, 266);
            this.tabBarangKonsumsi.TabIndex = 3;
            this.tabBarangKonsumsi.Text = "Barang Konsumsi";
            this.dgvBarangKonsumsi.BackgroundColor = System.Drawing.SystemColors.ButtonFace;
            this.dgvBarangKonsumsi.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle7.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle7.BackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle7.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            dataGridViewCellStyle7.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle7.SelectionBackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle7.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle7.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvBarangKonsumsi.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle7;
            this.dgvBarangKonsumsi.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dataGridViewCellStyle8.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle8.BackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle8.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            dataGridViewCellStyle8.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            dataGridViewCellStyle8.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle8.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle8.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvBarangKonsumsi.DefaultCellStyle = dataGridViewCellStyle8;
            this.dgvBarangKonsumsi.EnableHeadersVisualStyles = false;
            this.dgvBarangKonsumsi.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.dgvBarangKonsumsi.GridColor = System.Drawing.SystemColors.ButtonFace;
            this.dgvBarangKonsumsi.Location = new System.Drawing.Point(3, 3);
            this.dgvBarangKonsumsi.Name = "dgvBarangKonsumsi";
            this.dgvBarangKonsumsi.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle9.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle9.BackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle9.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            dataGridViewCellStyle9.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle9.SelectionBackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle9.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle9.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvBarangKonsumsi.RowHeadersDefaultCellStyle = dataGridViewCellStyle9;
            this.dgvBarangKonsumsi.RowHeadersWidth = 62;
            this.dgvBarangKonsumsi.RowTemplate.Height = 28;
            this.dgvBarangKonsumsi.Size = new System.Drawing.Size(774, 260);
            this.dgvBarangKonsumsi.TabIndex = 31;
            this.tabMaintenanceAlatLaundry.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.tabMaintenanceAlatLaundry.Controls.Add(this.dgvMaintenanceAlatLaundry);
            this.tabMaintenanceAlatLaundry.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tabMaintenanceAlatLaundry.Location = new System.Drawing.Point(4, 26);
            this.tabMaintenanceAlatLaundry.Name = "tabMaintenanceAlatLaundry";
            this.tabMaintenanceAlatLaundry.Size = new System.Drawing.Size(779, 266);
            this.tabMaintenanceAlatLaundry.TabIndex = 4;
            this.tabMaintenanceAlatLaundry.Text = "Maintenance Alat Laundry";
            this.dgvMaintenanceAlatLaundry.BackgroundColor = System.Drawing.SystemColors.ButtonFace;
            this.dgvMaintenanceAlatLaundry.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle10.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle10.BackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle10.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            dataGridViewCellStyle10.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle10.SelectionBackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle10.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle10.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvMaintenanceAlatLaundry.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle10;
            this.dgvMaintenanceAlatLaundry.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dataGridViewCellStyle11.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle11.BackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle11.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            dataGridViewCellStyle11.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            dataGridViewCellStyle11.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle11.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle11.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvMaintenanceAlatLaundry.DefaultCellStyle = dataGridViewCellStyle11;
            this.dgvMaintenanceAlatLaundry.EnableHeadersVisualStyles = false;
            this.dgvMaintenanceAlatLaundry.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.dgvMaintenanceAlatLaundry.GridColor = System.Drawing.SystemColors.ButtonFace;
            this.dgvMaintenanceAlatLaundry.Location = new System.Drawing.Point(3, 3);
            this.dgvMaintenanceAlatLaundry.Name = "dgvMaintenanceAlatLaundry";
            this.dgvMaintenanceAlatLaundry.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle12.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle12.BackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle12.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            dataGridViewCellStyle12.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle12.SelectionBackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle12.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle12.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvMaintenanceAlatLaundry.RowHeadersDefaultCellStyle = dataGridViewCellStyle12;
            this.dgvMaintenanceAlatLaundry.RowHeadersWidth = 62;
            this.dgvMaintenanceAlatLaundry.RowTemplate.Height = 28;
            this.dgvMaintenanceAlatLaundry.Size = new System.Drawing.Size(774, 260);
            this.dgvMaintenanceAlatLaundry.TabIndex = 32;
            this.tabTransaksi.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(242)))), ((int)(((byte)(242)))), ((int)(((byte)(242)))));
            this.tabTransaksi.Controls.Add(this.dgvTransaksi);
            this.tabTransaksi.ForeColor = System.Drawing.SystemColors.ControlText;
            this.tabTransaksi.Location = new System.Drawing.Point(4, 26);
            this.tabTransaksi.Name = "tabTransaksi";
            this.tabTransaksi.Size = new System.Drawing.Size(779, 266);
            this.tabTransaksi.TabIndex = 2;
            this.tabTransaksi.Text = "Transaksi";
            this.dgvTransaksi.BackgroundColor = System.Drawing.SystemColors.ButtonFace;
            this.dgvTransaksi.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle13.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle13.BackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle13.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            dataGridViewCellStyle13.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle13.SelectionBackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle13.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle13.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvTransaksi.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle13;
            this.dgvTransaksi.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dataGridViewCellStyle14.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle14.BackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle14.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            dataGridViewCellStyle14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(222)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
            dataGridViewCellStyle14.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle14.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle14.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvTransaksi.DefaultCellStyle = dataGridViewCellStyle14;
            this.dgvTransaksi.EnableHeadersVisualStyles = false;
            this.dgvTransaksi.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            this.dgvTransaksi.GridColor = System.Drawing.SystemColors.ButtonFace;
            this.dgvTransaksi.Location = new System.Drawing.Point(3, 3);
            this.dgvTransaksi.Name = "dgvTransaksi";
            this.dgvTransaksi.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.Single;
            dataGridViewCellStyle15.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle15.BackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle15.Font = new System.Drawing.Font("Roboto", 14F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Pixel);
            dataGridViewCellStyle15.ForeColor = System.Drawing.SystemColors.ControlText;
            dataGridViewCellStyle15.SelectionBackColor = System.Drawing.SystemColors.ControlLightLight;
            dataGridViewCellStyle15.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle15.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvTransaksi.RowHeadersDefaultCellStyle = dataGridViewCellStyle15;
            this.dgvTransaksi.RowHeadersWidth = 62;
            this.dgvTransaksi.RowTemplate.Height = 28;
            this.dgvTransaksi.Size = new System.Drawing.Size(774, 260);
            this.dgvTransaksi.TabIndex = 0;
            this.AutoScaleDimensions = new System.Drawing.SizeF(9F, 20F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(800, 450);
            this.Controls.Add(this.tabPreview);
            this.Controls.Add(this.lblLastBackup);
            this.Controls.Add(this.pbBR);
            this.Controls.Add(this.btnShowCachePelanggan);
            this.Controls.Add(this.btnRefreshDataPelanggan);
            this.Controls.Add(this.btnBackup);
            this.Controls.Add(this.btnRestore);
            this.Controls.Add(this.btnKembali);
            this.Name = "FormBAK";
            this.Opacity = 1D;
            this.Text = "Backup Restore";
            this.Load += new System.EventHandler(this.FormBAK_Load);
            this.Controls.SetChildIndex(this.btnKembali, 0);
            this.Controls.SetChildIndex(this.btnRestore, 0);
            this.Controls.SetChildIndex(this.btnBackup, 0);
            this.Controls.SetChildIndex(this.btnRefreshDataPelanggan, 0);
            this.Controls.SetChildIndex(this.btnShowCachePelanggan, 0);
            this.Controls.SetChildIndex(this.pbBR, 0);
            this.Controls.SetChildIndex(this.lblLastBackup, 0);
            this.Controls.SetChildIndex(this.tabPreview, 0);
            this.Controls.SetChildIndex(this.themeSwitch, 0);
            this.tabPreview.ResumeLayout(false);
            this.tabPelanggan.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvPelanggan)).EndInit();
            this.tabSepatu.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvSepatu)).EndInit();
            this.tabBarangKonsumsi.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvBarangKonsumsi)).EndInit();
            this.tabMaintenanceAlatLaundry.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvMaintenanceAlatLaundry)).EndInit();
            this.tabTransaksi.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dgvTransaksi)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.SaveFileDialog sfdBackup;
        private System.Windows.Forms.OpenFileDialog ofdRestore;
        private ManajemenLaundrySepatu.WinForms.Helpers.MyMaterialButton btnShowCachePelanggan;
        private ManajemenLaundrySepatu.WinForms.Helpers.MyMaterialButton btnRefreshDataPelanggan;
        private ManajemenLaundrySepatu.WinForms.Helpers.MyMaterialButton btnBackup;
        private ManajemenLaundrySepatu.WinForms.Helpers.MyMaterialButton btnRestore;
        private ManajemenLaundrySepatu.WinForms.Helpers.MyMaterialButton btnKembali;
        private System.Windows.Forms.ProgressBar pbBR;
        private MaterialSkin.Controls.MaterialLabel lblLastBackup;
        private System.Windows.Forms.TabControl tabPreview;
        private System.Windows.Forms.TabPage tabPelanggan;
        private System.Windows.Forms.TabPage tabSepatu;
        private System.Windows.Forms.DataGridView dgvPelanggan;
        private System.Windows.Forms.TabPage tabBarangKonsumsi;
        private System.Windows.Forms.TabPage tabMaintenanceAlatLaundry;
        private System.Windows.Forms.TabPage tabTransaksi;
        private System.Windows.Forms.DataGridView dgvSepatu;
        private System.Windows.Forms.DataGridView dgvBarangKonsumsi;
        private System.Windows.Forms.DataGridView dgvMaintenanceAlatLaundry;
        private System.Windows.Forms.DataGridView dgvTransaksi;
    }
}